version: 2
jobs:
  build-lfs:
    working_directory: ~/luminescent-dreams/emseries
    parallelism: 1
    shell: /bin/bash --login

    docker:
    - image: savannidgerinel/rust:latest

    steps:
    - checkout

    - restore_cache:
        keys:
          # This branch if available
          - dep-{{ .Branch }}-
          # Default branch if not
          - dep-sol-

    - run: cargo build

    - save_cache:
        key: dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cargo

    - run: mkdir var
    - run: cargo test

    - save_cache:
        key: dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cargo

  build-nix:
    working_directory: ~/luminescent-dreams/emseries
    parallelism: 1

    docker:
    - image: nixos/nix

    steps:
    - checkout
    - run: nix-build ./Cargo.nix -A emseries

workflows:
  version: 2
  build_all:
    jobs:
      - build-lfs
      - build-nix


